name: 'Build and deploy ASP.Net Core app to Azure Web App: mottubracelet-rm558186'

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore MottuBracelet/MottuBracelet.csproj

    - name: Build with dotnet
      run: dotnet build MottuBracelet/MottuBracelet.csproj --configuration Release

    - name: Publish project
      run: dotnet publish MottuBracelet/MottuBracelet.csproj -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mottubracelet-rm558186'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b441e8ca41ea47dcb3e272be7e932586 }}
        package: ./publish
      env:
        ConnectionStrings__DefaultConnection: ${{ secrets.DefaultConnection }}
